### ISSUE TITLE
Meta: Improve test coverages

### ISSUE THREAD

**Issue by yookoala** [yookoala/dragdrop-components#12]
Should cover
- [ ] expectation to touch-drag shadow (i.e. position).
- [ ] expectation to touch arrangement.
- [ ] expectation to multiple touch point.
